Github actions: add an OpenCL build
kotekan/kotekan pull request #1137
Opened 2023-10-02 18:06 UTC by dstndstn

2023-10-02 18:49 UTC, dstndstn commented
I just copied the `build-full-tests-2204` target to `build-opencl-2204` and changed the `cmake` command to turn off CUDA and turn on OpenCL.  Since the container has the required OpenCL libraries, this just worked!  Like the `full-tests` run, this runs the python parallel and Boost tests -- I don't know if we need those -- do they test anything that isn't tested in the `full-tests` build?

2023-10-03 16:26 UTC, jbmertens commented
This is great! There's now a node with a couple GPUs on it, along with a runner, on sky. I haven't had a chance to really test it yet, but this looks like a good first test. Could you change the runs-on to `runs-on: self-hosted`?

Also just a note, the boost tests haven't been running correctly on 22.04. Still need to investigate that.

2023-10-03 16:28 UTC, jbmertens requested changes

2023-10-03 16:28 UTC, jbmertens commented on .github/workflows/main.yml
> +    runs-on: ubuntu-latest
Change to `runs-on: self-hosted`

2023-10-03 16:28 UTC, jbmertens commented on .github/workflows/main.yml
> +      if: env.RUN_2204_BOOST_TESTS # These aren't working, so for now only run them upon request.
Just leaving a note to come back to this (#1117)

2023-10-05 19:44 UTC, dstndstn commented
Hi @jbmertens , sorry for not replying sooner!  The OpenCL will actually build on Github's CI infrastructure.  The tests won't do anything, of course :) but I think it would be useful to keep the build to make sure we don't break it (my current ticket was breaking it big time!).

2023-10-05 19:51 UTC, jbmertens commented
Ok, thanks @dstndstn! It looks like the build is failing on the local runner, which will take some debugging, but I'll address that in a separate PR. So this one looks good to go!

2023-10-05 19:52 UTC, jbmertens approved these changes

2023-10-05 20:14 UTC, dstndstn commented
Awesome, thank you!

2023-10-05 20:14 UTC, merged