Export data quality metric
kotekan/kotekan pull request #830
Opened 2020-09-24 21:06 UTC by james-s-willis

I think this is ready to review, though I'm not sure on the config file change.

2020-09-28 21:49 UTC, jrs65 requested changes

2020-09-28 21:49 UTC, jrs65 commented on lib/stages/DataQuality.cpp
> +    const stackState* ss = sstate_fut.get();
I think there's no point doing an async call here as you don't do anything in the middle. Might as well just do a normal blocking call.

2020-09-28 21:49 UTC, jrs65 commented on lib/stages/DataQuality.cpp
> +            auto var = (frame.weight[i] == 0 ? 0.0 : frame.weight[i]);
I'm pretty sure this should be:
```suggestion
            auto var = (frame.weight[i] == 0 ? 0.0 : 1.0 / frame.weight[i]);
```

2020-09-28 21:49 UTC, jrs65 commented on lib/stages/DataQuality.cpp
> +        FATAL_ERROR("Couldn't find stackState ancestor of dataset "
You should use the `fingerprint` technique in here. The way you have this implemented at the moment, you're going  to regenerate the alphas every time the dataset ID changes, which is every 10s at the moment, but stack state never changes.

In theory you could just use the stack state hash for that purpose, but we may eventually recalculate when the flags change too, so I would go straight to the fingerprint method.

2020-09-28 21:49 UTC, jrs65 commented on lib/stages/DataQuality.hpp
> + *
Make sure to document the metrics exported.

2020-09-29 15:58 UTC, james-s-willis commented
@jrs65 I've addressed your review comments.

2020-09-30 18:43 UTC, jrs65 requested changes
Oh oops. I write this review yesterday, but forgot to send it!

2020-09-30 21:06 UTC, jrs65 commented on lib/stages/DataQuality.cpp
> +    _num_elements = config.get<uint32_t>(unique_name, "num_elements");
Ah okay. I think there was a mistake in my description of the algorithm. I'll fix it in the parent issue, but basically: alpha = counts**2 / sum(counts)**2

2020-09-30 21:06 UTC, jrs65 commented on lib/stages/DataQuality.cpp
> +    _num_elements = config.get<uint32_t>(unique_name, "num_elements");
So I don't think you need `_num_elements` because of that.

2020-09-30 21:25 UTC, james-s-willis commented
@jrs65 I think I have fixed it now

2020-09-30 22:03 UTC, jrs65 reviewed
Looking good. The only thing left is to change to the correct algorithm for the alpha as my initial version had a mistake (sorry!), and then remove `_num_elements`. Details are in a comment.

2020-09-30 22:03 UTC, jrs65 commented on lib/stages/DataQuality.cpp
> +        auto fprint = dm.fingerprint(ds_id, {"stack"});
I would consider populating a ds_id -> fprint map here, though I don't think it's a must do. The fingerprint calculation involves some json manipulation which probably isn't great to do every single time. It's probably fine for our purposes at the moment, though if you decide not to change it we should look at the performance while testing.

2020-10-01 16:12 UTC, james-s-willis commented
@jrs65 I've added a map of `dataset_id` -> `fingerprint` and fixed the alpha calculation.

2020-10-01 16:57 UTC, jrs65 approved these changes
Great work. Thanks @james-s-willis

2020-10-02 18:32 UTC, andrerenard approved these changes

2020-10-02 19:05 UTC, merged