Add cpu monitor not-started message
kotekan/kotekan pull request #980
Opened 2021-07-30 15:09 UTC by Jintao-Xu

2021-07-30 15:26 UTC, james-s-willis approved these changes
Looks good to me

2021-07-30 16:15 UTC, andrerenard requested changes

2021-07-30 16:15 UTC, andrerenard commented on lib/core/cpuMonitor.cpp
> +        conn.send_text_reply("CPU monitor has not been started.");
I would sent this as a JSON formatted object. That way you don't have to check if the data is parsable or not, just parse as normal, and then look for an error string.

2021-08-03 18:03 UTC, andrerenard approved these changes

2021-08-03 18:54 UTC, merged